/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.group20.docker.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.group20.docker.ui.internal.DockerActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DockerExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(DockerActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		DockerActivator activator = DockerActivator.getInstance();
		return activator != null ? activator.getInjector(DockerActivator.UK_AC_KCL_INF_GROUP20_DOCKER_DOCKER) : null;
	}

}
