/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.group20.docker


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DockerStandaloneSetup extends DockerStandaloneSetupGenerated {

	def static void doSetup() {
		new DockerStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
