/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.group20.docker.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class DockerQuickfixProvider extends DefaultQuickfixProvider {
}
