/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.group20.docker.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import uk.ac.kcl.inf.group20.docker.ide.contentassist.antlr.internal.InternalDockerParser;
import uk.ac.kcl.inf.group20.docker.services.DockerGrammarAccess;

public class DockerParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DockerGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DockerGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStatementsAccess().getAlternatives(), "rule__Statements__Alternatives");
			builder.put(grammarAccess.getImageOptionsAccess().getAlternatives(), "rule__ImageOptions__Alternatives");
			builder.put(grammarAccess.getSourceOptionAccess().getAlternatives(), "rule__SourceOption__Alternatives");
			builder.put(grammarAccess.getCommitOptionsAccess().getAlternatives(), "rule__CommitOptions__Alternatives");
			builder.put(grammarAccess.getLogOptionsAccess().getAlternatives(), "rule__LogOptions__Alternatives");
			builder.put(grammarAccess.getEventOptionsAccess().getAlternatives(), "rule__EventOptions__Alternatives");
			builder.put(grammarAccess.getInspectOptionsAccess().getAlternatives(), "rule__InspectOptions__Alternatives");
			builder.put(grammarAccess.getPsOptionsAccess().getAlternatives(), "rule__PsOptions__Alternatives");
			builder.put(grammarAccess.getRunOptionAccess().getAlternatives(), "rule__RunOption__Alternatives");
			builder.put(grammarAccess.getRemoveImageOptionsAccess().getAlternatives(), "rule__RemoveImageOptions__Alternatives");
			builder.put(grammarAccess.getLinkOptionAccess().getAlternatives(), "rule__LinkOption__Alternatives");
			builder.put(grammarAccess.getSigOptionAccess().getAlternatives(), "rule__SigOption__Alternatives");
			builder.put(grammarAccess.getAttachOptionAccess().getAlternatives(), "rule__AttachOption__Alternatives");
			builder.put(grammarAccess.getExecOptionAccess().getAlternatives(), "rule__ExecOption__Alternatives");
			builder.put(grammarAccess.getKillOptionAccess().getAlternatives(), "rule__KillOption__Alternatives");
			builder.put(grammarAccess.getRmOptionsAccess().getAlternatives(), "rule__RmOptions__Alternatives");
			builder.put(grammarAccess.getRunorCreateAccess().getAlternatives(), "rule__RunorCreate__Alternatives");
			builder.put(grammarAccess.getImageAccess().getAlternatives(), "rule__Image__Alternatives");
			builder.put(grammarAccess.getOutTypeAccess().getAlternatives(), "rule__OutType__Alternatives");
			builder.put(grammarAccess.getRemoveImageStatementAccess().getGroup(), "rule__RemoveImageStatement__Group__0");
			builder.put(grammarAccess.getImageStatementAccess().getGroup(), "rule__ImageStatement__Group__0");
			builder.put(grammarAccess.getImageOptionsAccess().getGroup_0(), "rule__ImageOptions__Group_0__0");
			builder.put(grammarAccess.getImageOptionsAccess().getGroup_1(), "rule__ImageOptions__Group_1__0");
			builder.put(grammarAccess.getImageOptionsAccess().getGroup_2(), "rule__ImageOptions__Group_2__0");
			builder.put(grammarAccess.getImageOptionsAccess().getGroup_3(), "rule__ImageOptions__Group_3__0");
			builder.put(grammarAccess.getImageOptionsAccess().getGroup_4(), "rule__ImageOptions__Group_4__0");
			builder.put(grammarAccess.getImageOptionsAccess().getGroup_5(), "rule__ImageOptions__Group_5__0");
			builder.put(grammarAccess.getDiffStatementAccess().getGroup(), "rule__DiffStatement__Group__0");
			builder.put(grammarAccess.getCpStatementAccess().getGroup(), "rule__CpStatement__Group__0");
			builder.put(grammarAccess.getCommitStatementAccess().getGroup(), "rule__CommitStatement__Group__0");
			builder.put(grammarAccess.getCommitOptionsAccess().getGroup_0(), "rule__CommitOptions__Group_0__0");
			builder.put(grammarAccess.getCommitOptionsAccess().getGroup_1(), "rule__CommitOptions__Group_1__0");
			builder.put(grammarAccess.getCommitOptionsAccess().getGroup_2(), "rule__CommitOptions__Group_2__0");
			builder.put(grammarAccess.getCommitOptionsAccess().getGroup_3(), "rule__CommitOptions__Group_3__0");
			builder.put(grammarAccess.getPortStatementAccess().getGroup(), "rule__PortStatement__Group__0");
			builder.put(grammarAccess.getExportStatementAccess().getGroup(), "rule__ExportStatement__Group__0");
			builder.put(grammarAccess.getWaitStatementAccess().getGroup(), "rule__WaitStatement__Group__0");
			builder.put(grammarAccess.getLogsStatementAccess().getGroup(), "rule__LogsStatement__Group__0");
			builder.put(grammarAccess.getLogOptionsAccess().getGroup_0(), "rule__LogOptions__Group_0__0");
			builder.put(grammarAccess.getLogOptionsAccess().getGroup_1(), "rule__LogOptions__Group_1__0");
			builder.put(grammarAccess.getLogOptionsAccess().getGroup_2(), "rule__LogOptions__Group_2__0");
			builder.put(grammarAccess.getLogOptionsAccess().getGroup_3(), "rule__LogOptions__Group_3__0");
			builder.put(grammarAccess.getEventStatementAccess().getGroup(), "rule__EventStatement__Group__0");
			builder.put(grammarAccess.getEventOptionsAccess().getGroup_0(), "rule__EventOptions__Group_0__0");
			builder.put(grammarAccess.getEventOptionsAccess().getGroup_1(), "rule__EventOptions__Group_1__0");
			builder.put(grammarAccess.getEventOptionsAccess().getGroup_2(), "rule__EventOptions__Group_2__0");
			builder.put(grammarAccess.getAttachStatementAccess().getGroup(), "rule__AttachStatement__Group__0");
			builder.put(grammarAccess.getInspectStatementAccess().getGroup(), "rule__InspectStatement__Group__0");
			builder.put(grammarAccess.getInspectOptionsAccess().getGroup_0(), "rule__InspectOptions__Group_0__0");
			builder.put(grammarAccess.getInspectOptionsAccess().getGroup_2(), "rule__InspectOptions__Group_2__0");
			builder.put(grammarAccess.getPsStatementAccess().getGroup(), "rule__PsStatement__Group__0");
			builder.put(grammarAccess.getPsOptionsAccess().getGroup_2(), "rule__PsOptions__Group_2__0");
			builder.put(grammarAccess.getPsOptionsAccess().getGroup_3(), "rule__PsOptions__Group_3__0");
			builder.put(grammarAccess.getPsOptionsAccess().getGroup_5(), "rule__PsOptions__Group_5__0");
			builder.put(grammarAccess.getExecStatementAccess().getGroup(), "rule__ExecStatement__Group__0");
			builder.put(grammarAccess.getUnpauseStatementAccess().getGroup(), "rule__UnpauseStatement__Group__0");
			builder.put(grammarAccess.getPauseStatementAccess().getGroup(), "rule__PauseStatement__Group__0");
			builder.put(grammarAccess.getRestartStatementAccess().getGroup(), "rule__RestartStatement__Group__0");
			builder.put(grammarAccess.getStopStatementAccess().getGroup(), "rule__StopStatement__Group__0");
			builder.put(grammarAccess.getStartStatementAccess().getGroup(), "rule__StartStatement__Group__0");
			builder.put(grammarAccess.getKillStatementAccess().getGroup(), "rule__KillStatement__Group__0");
			builder.put(grammarAccess.getRemoveStatementAccess().getGroup(), "rule__RemoveStatement__Group__0");
			builder.put(grammarAccess.getRunCreateStatementAccess().getGroup(), "rule__RunCreateStatement__Group__0");
			builder.put(grammarAccess.getRunOptionAccess().getGroup_0(), "rule__RunOption__Group_0__0");
			builder.put(grammarAccess.getRunOptionAccess().getGroup_1(), "rule__RunOption__Group_1__0");
			builder.put(grammarAccess.getRunOptionAccess().getGroup_2(), "rule__RunOption__Group_2__0");
			builder.put(grammarAccess.getRunOptionAccess().getGroup_3(), "rule__RunOption__Group_3__0");
			builder.put(grammarAccess.getRunOptionAccess().getGroup_4(), "rule__RunOption__Group_4__0");
			builder.put(grammarAccess.getRunOptionAccess().getGroup_5(), "rule__RunOption__Group_5__0");
			builder.put(grammarAccess.getRunOptionAccess().getGroup_6(), "rule__RunOption__Group_6__0");
			builder.put(grammarAccess.getRunOptionAccess().getGroup_7(), "rule__RunOption__Group_7__0");
			builder.put(grammarAccess.getRunOptionAccess().getGroup_8(), "rule__RunOption__Group_8__0");
			builder.put(grammarAccess.getRunOptionAccess().getGroup_9(), "rule__RunOption__Group_9__0");
			builder.put(grammarAccess.getRunOptionAccess().getGroup_10(), "rule__RunOption__Group_10__0");
			builder.put(grammarAccess.getRunOptionAccess().getGroup_11(), "rule__RunOption__Group_11__0");
			builder.put(grammarAccess.getContainerNameDeclarationAccess().getGroup(), "rule__ContainerNameDeclaration__Group__0");
			builder.put(grammarAccess.getModelAccess().getStatementsAssignment(), "rule__Model__StatementsAssignment");
			builder.put(grammarAccess.getRemoveImageStatementAccess().getRemoveimageOptionsAssignment_1(), "rule__RemoveImageStatement__RemoveimageOptionsAssignment_1");
			builder.put(grammarAccess.getRemoveImageStatementAccess().getImageAssignment_2(), "rule__RemoveImageStatement__ImageAssignment_2");
			builder.put(grammarAccess.getImageStatementAccess().getImageOptionsAssignment_1(), "rule__ImageStatement__ImageOptionsAssignment_1");
			builder.put(grammarAccess.getImageStatementAccess().getRepositoryAssignment_2(), "rule__ImageStatement__RepositoryAssignment_2");
			builder.put(grammarAccess.getImageOptionsAccess().getOptionAssignment_0_1(), "rule__ImageOptions__OptionAssignment_0_1");
			builder.put(grammarAccess.getImageOptionsAccess().getOptionAssignment_1_1(), "rule__ImageOptions__OptionAssignment_1_1");
			builder.put(grammarAccess.getImageOptionsAccess().getOptionAssignment_2_0(), "rule__ImageOptions__OptionAssignment_2_0");
			builder.put(grammarAccess.getImageOptionsAccess().getConditionAssignment_2_1(), "rule__ImageOptions__ConditionAssignment_2_1");
			builder.put(grammarAccess.getImageOptionsAccess().getOptionAssignment_3_0(), "rule__ImageOptions__OptionAssignment_3_0");
			builder.put(grammarAccess.getImageOptionsAccess().getFormatsAssignment_3_1(), "rule__ImageOptions__FormatsAssignment_3_1");
			builder.put(grammarAccess.getImageOptionsAccess().getOptionAssignment_4_1(), "rule__ImageOptions__OptionAssignment_4_1");
			builder.put(grammarAccess.getImageOptionsAccess().getOptionAssignment_5_1(), "rule__ImageOptions__OptionAssignment_5_1");
			builder.put(grammarAccess.getDiffStatementAccess().getContainerNameAssignment_1(), "rule__DiffStatement__ContainerNameAssignment_1");
			builder.put(grammarAccess.getCpStatementAccess().getLinkAssignment_1(), "rule__CpStatement__LinkAssignment_1");
			builder.put(grammarAccess.getCpStatementAccess().getSourceAssignment_2(), "rule__CpStatement__SourceAssignment_2");
			builder.put(grammarAccess.getCpStatementAccess().getDestinationAssignment_3(), "rule__CpStatement__DestinationAssignment_3");
			builder.put(grammarAccess.getSourceOptionAccess().getOption1Assignment_0(), "rule__SourceOption__Option1Assignment_0");
			builder.put(grammarAccess.getSourceOptionAccess().getOption2Assignment_1(), "rule__SourceOption__Option2Assignment_1");
			builder.put(grammarAccess.getCommitStatementAccess().getCommitOptionsAssignment_1(), "rule__CommitStatement__CommitOptionsAssignment_1");
			builder.put(grammarAccess.getCommitStatementAccess().getContainerNameAssignment_2(), "rule__CommitStatement__ContainerNameAssignment_2");
			builder.put(grammarAccess.getCommitStatementAccess().getRepositoryAssignment_3(), "rule__CommitStatement__RepositoryAssignment_3");
			builder.put(grammarAccess.getCommitOptionsAccess().getOptionAssignment_0_0(), "rule__CommitOptions__OptionAssignment_0_0");
			builder.put(grammarAccess.getCommitOptionsAccess().getAuthorAssignment_0_1(), "rule__CommitOptions__AuthorAssignment_0_1");
			builder.put(grammarAccess.getCommitOptionsAccess().getOptionAssignment_1_1(), "rule__CommitOptions__OptionAssignment_1_1");
			builder.put(grammarAccess.getCommitOptionsAccess().getOptionAssignment_2_0(), "rule__CommitOptions__OptionAssignment_2_0");
			builder.put(grammarAccess.getCommitOptionsAccess().getDescriptionAssignment_2_1(), "rule__CommitOptions__DescriptionAssignment_2_1");
			builder.put(grammarAccess.getCommitOptionsAccess().getOptionAssignment_3_1(), "rule__CommitOptions__OptionAssignment_3_1");
			builder.put(grammarAccess.getPortStatementAccess().getContainerNameAssignment_1(), "rule__PortStatement__ContainerNameAssignment_1");
			builder.put(grammarAccess.getPortStatementAccess().getPrivate_portAssignment_2(), "rule__PortStatement__Private_portAssignment_2");
			builder.put(grammarAccess.getExportStatementAccess().getFile_pathAssignment_1(), "rule__ExportStatement__File_pathAssignment_1");
			builder.put(grammarAccess.getExportStatementAccess().getContainerNameAssignment_2(), "rule__ExportStatement__ContainerNameAssignment_2");
			builder.put(grammarAccess.getWaitStatementAccess().getContainerNameAssignment_1(), "rule__WaitStatement__ContainerNameAssignment_1");
			builder.put(grammarAccess.getLogsStatementAccess().getLogOptionsAssignment_1(), "rule__LogsStatement__LogOptionsAssignment_1");
			builder.put(grammarAccess.getLogsStatementAccess().getContainerNameAssignment_2(), "rule__LogsStatement__ContainerNameAssignment_2");
			builder.put(grammarAccess.getLogOptionsAccess().getOptionAssignment_0_1(), "rule__LogOptions__OptionAssignment_0_1");
			builder.put(grammarAccess.getLogOptionsAccess().getOptionAssignment_1_0(), "rule__LogOptions__OptionAssignment_1_0");
			builder.put(grammarAccess.getLogOptionsAccess().getTimeAssignment_1_1(), "rule__LogOptions__TimeAssignment_1_1");
			builder.put(grammarAccess.getLogOptionsAccess().getOptionAssignment_2_1(), "rule__LogOptions__OptionAssignment_2_1");
			builder.put(grammarAccess.getLogOptionsAccess().getOptionAssignment_3_0(), "rule__LogOptions__OptionAssignment_3_0");
			builder.put(grammarAccess.getLogOptionsAccess().getNumberAssignment_3_1(), "rule__LogOptions__NumberAssignment_3_1");
			builder.put(grammarAccess.getEventStatementAccess().getEventOptionsAssignment_1(), "rule__EventStatement__EventOptionsAssignment_1");
			builder.put(grammarAccess.getEventOptionsAccess().getOptionAssignment_0_0(), "rule__EventOptions__OptionAssignment_0_0");
			builder.put(grammarAccess.getEventOptionsAccess().getCommandsAssignment_0_1(), "rule__EventOptions__CommandsAssignment_0_1");
			builder.put(grammarAccess.getEventOptionsAccess().getOptionAssignment_1_0(), "rule__EventOptions__OptionAssignment_1_0");
			builder.put(grammarAccess.getEventOptionsAccess().getTimeSAssignment_1_1(), "rule__EventOptions__TimeSAssignment_1_1");
			builder.put(grammarAccess.getEventOptionsAccess().getOptionAssignment_2_0(), "rule__EventOptions__OptionAssignment_2_0");
			builder.put(grammarAccess.getEventOptionsAccess().getTimeUAssignment_2_1(), "rule__EventOptions__TimeUAssignment_2_1");
			builder.put(grammarAccess.getAttachStatementAccess().getAttachOptionAssignment_1(), "rule__AttachStatement__AttachOptionAssignment_1");
			builder.put(grammarAccess.getAttachStatementAccess().getContainerNameAssignment_2(), "rule__AttachStatement__ContainerNameAssignment_2");
			builder.put(grammarAccess.getInspectStatementAccess().getInspectOptionsAssignment_1(), "rule__InspectStatement__InspectOptionsAssignment_1");
			builder.put(grammarAccess.getInspectOptionsAccess().getOptionAssignment_0_0(), "rule__InspectOptions__OptionAssignment_0_0");
			builder.put(grammarAccess.getInspectOptionsAccess().getFormatsAssignment_0_1(), "rule__InspectOptions__FormatsAssignment_0_1");
			builder.put(grammarAccess.getInspectOptionsAccess().getOptionAssignment_1(), "rule__InspectOptions__OptionAssignment_1");
			builder.put(grammarAccess.getInspectOptionsAccess().getOptionAssignment_2_0(), "rule__InspectOptions__OptionAssignment_2_0");
			builder.put(grammarAccess.getInspectOptionsAccess().getTypesAssignment_2_1(), "rule__InspectOptions__TypesAssignment_2_1");
			builder.put(grammarAccess.getPsStatementAccess().getPsOptionsAssignment_1(), "rule__PsStatement__PsOptionsAssignment_1");
			builder.put(grammarAccess.getPsOptionsAccess().getOptionAssignment_0(), "rule__PsOptions__OptionAssignment_0");
			builder.put(grammarAccess.getPsOptionsAccess().getOptionAssignment_1(), "rule__PsOptions__OptionAssignment_1");
			builder.put(grammarAccess.getPsOptionsAccess().getOptionAssignment_2_0(), "rule__PsOptions__OptionAssignment_2_0");
			builder.put(grammarAccess.getPsOptionsAccess().getCommandsAssignment_2_1(), "rule__PsOptions__CommandsAssignment_2_1");
			builder.put(grammarAccess.getPsOptionsAccess().getOptionAssignment_3_0(), "rule__PsOptions__OptionAssignment_3_0");
			builder.put(grammarAccess.getPsOptionsAccess().getFormatsAssignment_3_1(), "rule__PsOptions__FormatsAssignment_3_1");
			builder.put(grammarAccess.getPsOptionsAccess().getOptionAssignment_4(), "rule__PsOptions__OptionAssignment_4");
			builder.put(grammarAccess.getPsOptionsAccess().getOptionAssignment_5_0(), "rule__PsOptions__OptionAssignment_5_0");
			builder.put(grammarAccess.getPsOptionsAccess().getNAssignment_5_1(), "rule__PsOptions__NAssignment_5_1");
			builder.put(grammarAccess.getPsOptionsAccess().getOptionAssignment_6(), "rule__PsOptions__OptionAssignment_6");
			builder.put(grammarAccess.getPsOptionsAccess().getOptionAssignment_7(), "rule__PsOptions__OptionAssignment_7");
			builder.put(grammarAccess.getPsOptionsAccess().getOptionAssignment_8(), "rule__PsOptions__OptionAssignment_8");
			builder.put(grammarAccess.getExecStatementAccess().getExecOptionsAssignment_1(), "rule__ExecStatement__ExecOptionsAssignment_1");
			builder.put(grammarAccess.getExecStatementAccess().getContainerNameAssignment_2(), "rule__ExecStatement__ContainerNameAssignment_2");
			builder.put(grammarAccess.getExecStatementAccess().getCommandsAssignment_3(), "rule__ExecStatement__CommandsAssignment_3");
			builder.put(grammarAccess.getUnpauseStatementAccess().getContainerNameAssignment_1(), "rule__UnpauseStatement__ContainerNameAssignment_1");
			builder.put(grammarAccess.getPauseStatementAccess().getContainerNameAssignment_1(), "rule__PauseStatement__ContainerNameAssignment_1");
			builder.put(grammarAccess.getRestartStatementAccess().getContainerNameAssignment_1(), "rule__RestartStatement__ContainerNameAssignment_1");
			builder.put(grammarAccess.getStopStatementAccess().getContainerNameAssignment_1(), "rule__StopStatement__ContainerNameAssignment_1");
			builder.put(grammarAccess.getStartStatementAccess().getContainerNameAssignment_1(), "rule__StartStatement__ContainerNameAssignment_1");
			builder.put(grammarAccess.getKillStatementAccess().getKillAssignment_0(), "rule__KillStatement__KillAssignment_0");
			builder.put(grammarAccess.getKillStatementAccess().getContainerNameAssignment_1(), "rule__KillStatement__ContainerNameAssignment_1");
			builder.put(grammarAccess.getRemoveStatementAccess().getRmOptionsAssignment_1(), "rule__RemoveStatement__RmOptionsAssignment_1");
			builder.put(grammarAccess.getRemoveStatementAccess().getContainerNameAssignment_2(), "rule__RemoveStatement__ContainerNameAssignment_2");
			builder.put(grammarAccess.getRunCreateStatementAccess().getOrderAssignment_0(), "rule__RunCreateStatement__OrderAssignment_0");
			builder.put(grammarAccess.getRunCreateStatementAccess().getRunOptionsAssignment_1(), "rule__RunCreateStatement__RunOptionsAssignment_1");
			builder.put(grammarAccess.getRunCreateStatementAccess().getImageAssignment_2(), "rule__RunCreateStatement__ImageAssignment_2");
			builder.put(grammarAccess.getRunCreateStatementAccess().getCommandsAssignment_3(), "rule__RunCreateStatement__CommandsAssignment_3");
			builder.put(grammarAccess.getRunOptionAccess().getConditionAssignment_0_0(), "rule__RunOption__ConditionAssignment_0_0");
			builder.put(grammarAccess.getRunOptionAccess().getOutTypeAssignment_0_1(), "rule__RunOption__OutTypeAssignment_0_1");
			builder.put(grammarAccess.getRunOptionAccess().getConditionAssignment_1_1(), "rule__RunOption__ConditionAssignment_1_1");
			builder.put(grammarAccess.getRunOptionAccess().getConditionAssignment_2_1(), "rule__RunOption__ConditionAssignment_2_1");
			builder.put(grammarAccess.getRunOptionAccess().getConditionAssignment_3_1(), "rule__RunOption__ConditionAssignment_3_1");
			builder.put(grammarAccess.getRunOptionAccess().getConditionAssignment_4_0(), "rule__RunOption__ConditionAssignment_4_0");
			builder.put(grammarAccess.getRunOptionAccess().getPortNameAssignment_4_1(), "rule__RunOption__PortNameAssignment_4_1");
			builder.put(grammarAccess.getRunOptionAccess().getConditionAssignment_5_1(), "rule__RunOption__ConditionAssignment_5_1");
			builder.put(grammarAccess.getRunOptionAccess().getConditionAssignment_6_0(), "rule__RunOption__ConditionAssignment_6_0");
			builder.put(grammarAccess.getRunOptionAccess().getServerAssignment_6_1(), "rule__RunOption__ServerAssignment_6_1");
			builder.put(grammarAccess.getRunOptionAccess().getConditionAssignment_7_0(), "rule__RunOption__ConditionAssignment_7_0");
			builder.put(grammarAccess.getRunOptionAccess().getDomainNameAssignment_7_1(), "rule__RunOption__DomainNameAssignment_7_1");
			builder.put(grammarAccess.getRunOptionAccess().getConditionAssignment_8_0(), "rule__RunOption__ConditionAssignment_8_0");
			builder.put(grammarAccess.getRunOptionAccess().getHostnameAssignment_8_1(), "rule__RunOption__HostnameAssignment_8_1");
			builder.put(grammarAccess.getRunOptionAccess().getConditionAssignment_9_0(), "rule__RunOption__ConditionAssignment_9_0");
			builder.put(grammarAccess.getRunOptionAccess().getEnvironmentVariableAssignment_9_1(), "rule__RunOption__EnvironmentVariableAssignment_9_1");
			builder.put(grammarAccess.getRunOptionAccess().getSetEnvironmentVariableAssignment_9_3(), "rule__RunOption__SetEnvironmentVariableAssignment_9_3");
			builder.put(grammarAccess.getRunOptionAccess().getConditionAssignment_10_0(), "rule__RunOption__ConditionAssignment_10_0");
			builder.put(grammarAccess.getRunOptionAccess().getConnectTypeAssignment_10_1(), "rule__RunOption__ConnectTypeAssignment_10_1");
			builder.put(grammarAccess.getRunOptionAccess().getConditionAssignment_11_0(), "rule__RunOption__ConditionAssignment_11_0");
			builder.put(grammarAccess.getRunOptionAccess().getContainerNameAssignment_11_1(), "rule__RunOption__ContainerNameAssignment_11_1");
			builder.put(grammarAccess.getContainerNameDeclarationAccess().getNameAssignment_1(), "rule__ContainerNameDeclaration__NameAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DockerGrammarAccess grammarAccess;

	@Override
	protected InternalDockerParser createParser() {
		InternalDockerParser result = new InternalDockerParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DockerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DockerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
