/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.group20.docker.docker.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uk.ac.kcl.inf.group20.docker.docker.DockerPackage;
import uk.ac.kcl.inf.group20.docker.docker.ImageOptions;
import uk.ac.kcl.inf.group20.docker.docker.ImageStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Image Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.impl.ImageStatementImpl#getImageOptions <em>Image Options</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.impl.ImageStatementImpl#getRepository <em>Repository</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ImageStatementImpl extends StatementsImpl implements ImageStatement
{
  /**
   * The cached value of the '{@link #getImageOptions() <em>Image Options</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImageOptions()
   * @generated
   * @ordered
   */
  protected EList<ImageOptions> imageOptions;

  /**
   * The default value of the '{@link #getRepository() <em>Repository</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRepository()
   * @generated
   * @ordered
   */
  protected static final String REPOSITORY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRepository() <em>Repository</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRepository()
   * @generated
   * @ordered
   */
  protected String repository = REPOSITORY_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ImageStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DockerPackage.Literals.IMAGE_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ImageOptions> getImageOptions()
  {
    if (imageOptions == null)
    {
      imageOptions = new EObjectContainmentEList<ImageOptions>(ImageOptions.class, this, DockerPackage.IMAGE_STATEMENT__IMAGE_OPTIONS);
    }
    return imageOptions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRepository()
  {
    return repository;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRepository(String newRepository)
  {
    String oldRepository = repository;
    repository = newRepository;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DockerPackage.IMAGE_STATEMENT__REPOSITORY, oldRepository, repository));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DockerPackage.IMAGE_STATEMENT__IMAGE_OPTIONS:
        return ((InternalEList<?>)getImageOptions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DockerPackage.IMAGE_STATEMENT__IMAGE_OPTIONS:
        return getImageOptions();
      case DockerPackage.IMAGE_STATEMENT__REPOSITORY:
        return getRepository();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DockerPackage.IMAGE_STATEMENT__IMAGE_OPTIONS:
        getImageOptions().clear();
        getImageOptions().addAll((Collection<? extends ImageOptions>)newValue);
        return;
      case DockerPackage.IMAGE_STATEMENT__REPOSITORY:
        setRepository((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DockerPackage.IMAGE_STATEMENT__IMAGE_OPTIONS:
        getImageOptions().clear();
        return;
      case DockerPackage.IMAGE_STATEMENT__REPOSITORY:
        setRepository(REPOSITORY_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DockerPackage.IMAGE_STATEMENT__IMAGE_OPTIONS:
        return imageOptions != null && !imageOptions.isEmpty();
      case DockerPackage.IMAGE_STATEMENT__REPOSITORY:
        return REPOSITORY_EDEFAULT == null ? repository != null : !REPOSITORY_EDEFAULT.equals(repository);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (repository: ");
    result.append(repository);
    result.append(')');
    return result.toString();
  }

} //ImageStatementImpl
