/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.group20.docker.docker.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.kcl.inf.group20.docker.docker.DockerPackage;
import uk.ac.kcl.inf.group20.docker.docker.InspectOptions;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Inspect Options</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.impl.InspectOptionsImpl#getOption <em>Option</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.impl.InspectOptionsImpl#getFormats <em>Formats</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.impl.InspectOptionsImpl#getTypes <em>Types</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InspectOptionsImpl extends MinimalEObjectImpl.Container implements InspectOptions
{
  /**
   * The default value of the '{@link #getOption() <em>Option</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOption()
   * @generated
   * @ordered
   */
  protected static final String OPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOption() <em>Option</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOption()
   * @generated
   * @ordered
   */
  protected String option = OPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getFormats() <em>Formats</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFormats()
   * @generated
   * @ordered
   */
  protected static final String FORMATS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFormats() <em>Formats</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFormats()
   * @generated
   * @ordered
   */
  protected String formats = FORMATS_EDEFAULT;

  /**
   * The default value of the '{@link #getTypes() <em>Types</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypes()
   * @generated
   * @ordered
   */
  protected static final String TYPES_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTypes() <em>Types</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypes()
   * @generated
   * @ordered
   */
  protected String types = TYPES_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InspectOptionsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DockerPackage.Literals.INSPECT_OPTIONS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOption()
  {
    return option;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOption(String newOption)
  {
    String oldOption = option;
    option = newOption;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DockerPackage.INSPECT_OPTIONS__OPTION, oldOption, option));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFormats()
  {
    return formats;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFormats(String newFormats)
  {
    String oldFormats = formats;
    formats = newFormats;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DockerPackage.INSPECT_OPTIONS__FORMATS, oldFormats, formats));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTypes()
  {
    return types;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTypes(String newTypes)
  {
    String oldTypes = types;
    types = newTypes;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DockerPackage.INSPECT_OPTIONS__TYPES, oldTypes, types));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DockerPackage.INSPECT_OPTIONS__OPTION:
        return getOption();
      case DockerPackage.INSPECT_OPTIONS__FORMATS:
        return getFormats();
      case DockerPackage.INSPECT_OPTIONS__TYPES:
        return getTypes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DockerPackage.INSPECT_OPTIONS__OPTION:
        setOption((String)newValue);
        return;
      case DockerPackage.INSPECT_OPTIONS__FORMATS:
        setFormats((String)newValue);
        return;
      case DockerPackage.INSPECT_OPTIONS__TYPES:
        setTypes((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DockerPackage.INSPECT_OPTIONS__OPTION:
        setOption(OPTION_EDEFAULT);
        return;
      case DockerPackage.INSPECT_OPTIONS__FORMATS:
        setFormats(FORMATS_EDEFAULT);
        return;
      case DockerPackage.INSPECT_OPTIONS__TYPES:
        setTypes(TYPES_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DockerPackage.INSPECT_OPTIONS__OPTION:
        return OPTION_EDEFAULT == null ? option != null : !OPTION_EDEFAULT.equals(option);
      case DockerPackage.INSPECT_OPTIONS__FORMATS:
        return FORMATS_EDEFAULT == null ? formats != null : !FORMATS_EDEFAULT.equals(formats);
      case DockerPackage.INSPECT_OPTIONS__TYPES:
        return TYPES_EDEFAULT == null ? types != null : !TYPES_EDEFAULT.equals(types);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (option: ");
    result.append(option);
    result.append(", formats: ");
    result.append(formats);
    result.append(", types: ");
    result.append(types);
    result.append(')');
    return result.toString();
  }

} //InspectOptionsImpl
