/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.group20.docker.docker.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uk.ac.kcl.inf.group20.docker.docker.DockerPackage;
import uk.ac.kcl.inf.group20.docker.docker.InspectOptions;
import uk.ac.kcl.inf.group20.docker.docker.InspectStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Inspect Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.impl.InspectStatementImpl#getInspectOptions <em>Inspect Options</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InspectStatementImpl extends StatementsImpl implements InspectStatement
{
  /**
   * The cached value of the '{@link #getInspectOptions() <em>Inspect Options</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInspectOptions()
   * @generated
   * @ordered
   */
  protected EList<InspectOptions> inspectOptions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InspectStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DockerPackage.Literals.INSPECT_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<InspectOptions> getInspectOptions()
  {
    if (inspectOptions == null)
    {
      inspectOptions = new EObjectContainmentEList<InspectOptions>(InspectOptions.class, this, DockerPackage.INSPECT_STATEMENT__INSPECT_OPTIONS);
    }
    return inspectOptions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DockerPackage.INSPECT_STATEMENT__INSPECT_OPTIONS:
        return ((InternalEList<?>)getInspectOptions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DockerPackage.INSPECT_STATEMENT__INSPECT_OPTIONS:
        return getInspectOptions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DockerPackage.INSPECT_STATEMENT__INSPECT_OPTIONS:
        getInspectOptions().clear();
        getInspectOptions().addAll((Collection<? extends InspectOptions>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DockerPackage.INSPECT_STATEMENT__INSPECT_OPTIONS:
        getInspectOptions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DockerPackage.INSPECT_STATEMENT__INSPECT_OPTIONS:
        return inspectOptions != null && !inspectOptions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //InspectStatementImpl
