/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.group20.docker.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DockerUiModule extends AbstractDockerUiModule {

	public DockerUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
