/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.group20.docker.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class DockerProposalProvider extends AbstractDockerProposalProvider {
}
