/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.group20.docker.docker;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attach Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.AttachStatement#getAttachOption <em>Attach Option</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.AttachStatement#getContainerName <em>Container Name</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getAttachStatement()
 * @model
 * @generated
 */
public interface AttachStatement extends Statements
{
  /**
   * Returns the value of the '<em><b>Attach Option</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.group20.docker.docker.AttachOption}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attach Option</em>' attribute.
   * @see uk.ac.kcl.inf.group20.docker.docker.AttachOption
   * @see #setAttachOption(AttachOption)
   * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getAttachStatement_AttachOption()
   * @model
   * @generated
   */
  AttachOption getAttachOption();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group20.docker.docker.AttachStatement#getAttachOption <em>Attach Option</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attach Option</em>' attribute.
   * @see uk.ac.kcl.inf.group20.docker.docker.AttachOption
   * @see #getAttachOption()
   * @generated
   */
  void setAttachOption(AttachOption value);

  /**
   * Returns the value of the '<em><b>Container Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Container Name</em>' reference.
   * @see #setContainerName(ContainerNameDeclaration)
   * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getAttachStatement_ContainerName()
   * @model
   * @generated
   */
  ContainerNameDeclaration getContainerName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group20.docker.docker.AttachStatement#getContainerName <em>Container Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Container Name</em>' reference.
   * @see #getContainerName()
   * @generated
   */
  void setContainerName(ContainerNameDeclaration value);

} // AttachStatement
