/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.group20.docker.docker;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exec Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.ExecStatement#getExecOptions <em>Exec Options</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.ExecStatement#getContainerName <em>Container Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.ExecStatement#getCommands <em>Commands</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getExecStatement()
 * @model
 * @generated
 */
public interface ExecStatement extends Statements
{
  /**
   * Returns the value of the '<em><b>Exec Options</b></em>' attribute list.
   * The list contents are of type {@link uk.ac.kcl.inf.group20.docker.docker.ExecOption}.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.group20.docker.docker.ExecOption}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exec Options</em>' attribute list.
   * @see uk.ac.kcl.inf.group20.docker.docker.ExecOption
   * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getExecStatement_ExecOptions()
   * @model unique="false"
   * @generated
   */
  EList<ExecOption> getExecOptions();

  /**
   * Returns the value of the '<em><b>Container Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Container Name</em>' reference.
   * @see #setContainerName(ContainerNameDeclaration)
   * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getExecStatement_ContainerName()
   * @model
   * @generated
   */
  ContainerNameDeclaration getContainerName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group20.docker.docker.ExecStatement#getContainerName <em>Container Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Container Name</em>' reference.
   * @see #getContainerName()
   * @generated
   */
  void setContainerName(ContainerNameDeclaration value);

  /**
   * Returns the value of the '<em><b>Commands</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands</em>' attribute.
   * @see #setCommands(String)
   * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getExecStatement_Commands()
   * @model
   * @generated
   */
  String getCommands();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group20.docker.docker.ExecStatement#getCommands <em>Commands</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Commands</em>' attribute.
   * @see #getCommands()
   * @generated
   */
  void setCommands(String value);

} // ExecStatement
