/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.group20.docker.docker;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Kill Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.KillStatement#getKill <em>Kill</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.KillStatement#getContainerName <em>Container Name</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getKillStatement()
 * @model
 * @generated
 */
public interface KillStatement extends Statements
{
  /**
   * Returns the value of the '<em><b>Kill</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.group20.docker.docker.KillOption}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kill</em>' attribute.
   * @see uk.ac.kcl.inf.group20.docker.docker.KillOption
   * @see #setKill(KillOption)
   * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getKillStatement_Kill()
   * @model
   * @generated
   */
  KillOption getKill();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group20.docker.docker.KillStatement#getKill <em>Kill</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kill</em>' attribute.
   * @see uk.ac.kcl.inf.group20.docker.docker.KillOption
   * @see #getKill()
   * @generated
   */
  void setKill(KillOption value);

  /**
   * Returns the value of the '<em><b>Container Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Container Name</em>' reference.
   * @see #setContainerName(ContainerNameDeclaration)
   * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getKillStatement_ContainerName()
   * @model
   * @generated
   */
  ContainerNameDeclaration getContainerName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group20.docker.docker.KillStatement#getContainerName <em>Container Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Container Name</em>' reference.
   * @see #getContainerName()
   * @generated
   */
  void setContainerName(ContainerNameDeclaration value);

} // KillStatement
