/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.group20.docker.docker;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Log Options</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.LogOptions#getOption <em>Option</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.LogOptions#getTime <em>Time</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.LogOptions#getNumber <em>Number</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getLogOptions()
 * @model
 * @generated
 */
public interface LogOptions extends EObject
{
  /**
   * Returns the value of the '<em><b>Option</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Option</em>' attribute.
   * @see #setOption(String)
   * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getLogOptions_Option()
   * @model
   * @generated
   */
  String getOption();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group20.docker.docker.LogOptions#getOption <em>Option</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Option</em>' attribute.
   * @see #getOption()
   * @generated
   */
  void setOption(String value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' attribute.
   * @see #setTime(String)
   * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getLogOptions_Time()
   * @model
   * @generated
   */
  String getTime();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group20.docker.docker.LogOptions#getTime <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' attribute.
   * @see #getTime()
   * @generated
   */
  void setTime(String value);

  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getLogOptions_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group20.docker.docker.LogOptions#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

} // LogOptions
