/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.group20.docker.docker;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Rm Options</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getRmOptions()
 * @model
 * @generated
 */
public enum RmOptions implements Enumerator
{
  /**
   * The '<em><b>No option</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NO_OPTION_VALUE
   * @generated
   * @ordered
   */
  NO_OPTION(0, "no_option", "no_option"),

  /**
   * The '<em><b>Force</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FORCE_VALUE
   * @generated
   * @ordered
   */
  FORCE(1, "force", "force"),

  /**
   * The '<em><b>Delete link</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DELETE_LINK_VALUE
   * @generated
   * @ordered
   */
  DELETE_LINK(2, "delete_link", "delete_link"),

  /**
   * The '<em><b>Delete volume</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DELETE_VOLUME_VALUE
   * @generated
   * @ordered
   */
  DELETE_VOLUME(3, "delete_volume", "delete_volume");

  /**
   * The '<em><b>No option</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NO_OPTION
   * @model name="no_option"
   * @generated
   * @ordered
   */
  public static final int NO_OPTION_VALUE = 0;

  /**
   * The '<em><b>Force</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FORCE
   * @model name="force"
   * @generated
   * @ordered
   */
  public static final int FORCE_VALUE = 1;

  /**
   * The '<em><b>Delete link</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DELETE_LINK
   * @model name="delete_link"
   * @generated
   * @ordered
   */
  public static final int DELETE_LINK_VALUE = 2;

  /**
   * The '<em><b>Delete volume</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DELETE_VOLUME
   * @model name="delete_volume"
   * @generated
   * @ordered
   */
  public static final int DELETE_VOLUME_VALUE = 3;

  /**
   * An array of all the '<em><b>Rm Options</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final RmOptions[] VALUES_ARRAY =
    new RmOptions[]
    {
      NO_OPTION,
      FORCE,
      DELETE_LINK,
      DELETE_VOLUME,
    };

  /**
   * A public read-only list of all the '<em><b>Rm Options</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<RmOptions> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Rm Options</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static RmOptions get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      RmOptions result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Rm Options</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static RmOptions getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      RmOptions result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Rm Options</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static RmOptions get(int value)
  {
    switch (value)
    {
      case NO_OPTION_VALUE: return NO_OPTION;
      case FORCE_VALUE: return FORCE;
      case DELETE_LINK_VALUE: return DELETE_LINK;
      case DELETE_VOLUME_VALUE: return DELETE_VOLUME;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private RmOptions(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //RmOptions
