/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.group20.docker.docker;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Export Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.ExportStatement#getFile_path <em>File path</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.ExportStatement#getContainerName <em>Container Name</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getExportStatement()
 * @model
 * @generated
 */
public interface ExportStatement extends Statements
{
  /**
   * Returns the value of the '<em><b>File path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>File path</em>' attribute.
   * @see #setFile_path(String)
   * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getExportStatement_File_path()
   * @model
   * @generated
   */
  String getFile_path();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group20.docker.docker.ExportStatement#getFile_path <em>File path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>File path</em>' attribute.
   * @see #getFile_path()
   * @generated
   */
  void setFile_path(String value);

  /**
   * Returns the value of the '<em><b>Container Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Container Name</em>' reference.
   * @see #setContainerName(ContainerNameDeclaration)
   * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getExportStatement_ContainerName()
   * @model
   * @generated
   */
  ContainerNameDeclaration getContainerName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group20.docker.docker.ExportStatement#getContainerName <em>Container Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Container Name</em>' reference.
   * @see #getContainerName()
   * @generated
   */
  void setContainerName(ContainerNameDeclaration value);

} // ExportStatement
