/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.group20.docker.docker;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Run Create Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.RunCreateStatement#getOrder <em>Order</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.RunCreateStatement#getRunOptions <em>Run Options</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.RunCreateStatement#getImage <em>Image</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group20.docker.docker.RunCreateStatement#getCommands <em>Commands</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getRunCreateStatement()
 * @model
 * @generated
 */
public interface RunCreateStatement extends Statements
{
  /**
   * Returns the value of the '<em><b>Order</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.group20.docker.docker.RunorCreate}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Order</em>' attribute.
   * @see uk.ac.kcl.inf.group20.docker.docker.RunorCreate
   * @see #setOrder(RunorCreate)
   * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getRunCreateStatement_Order()
   * @model
   * @generated
   */
  RunorCreate getOrder();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group20.docker.docker.RunCreateStatement#getOrder <em>Order</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Order</em>' attribute.
   * @see uk.ac.kcl.inf.group20.docker.docker.RunorCreate
   * @see #getOrder()
   * @generated
   */
  void setOrder(RunorCreate value);

  /**
   * Returns the value of the '<em><b>Run Options</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.group20.docker.docker.RunOption}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Run Options</em>' containment reference list.
   * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getRunCreateStatement_RunOptions()
   * @model containment="true"
   * @generated
   */
  EList<RunOption> getRunOptions();

  /**
   * Returns the value of the '<em><b>Image</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.group20.docker.docker.Image}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Image</em>' attribute.
   * @see uk.ac.kcl.inf.group20.docker.docker.Image
   * @see #setImage(Image)
   * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getRunCreateStatement_Image()
   * @model
   * @generated
   */
  Image getImage();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group20.docker.docker.RunCreateStatement#getImage <em>Image</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Image</em>' attribute.
   * @see uk.ac.kcl.inf.group20.docker.docker.Image
   * @see #getImage()
   * @generated
   */
  void setImage(Image value);

  /**
   * Returns the value of the '<em><b>Commands</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands</em>' attribute.
   * @see #setCommands(String)
   * @see uk.ac.kcl.inf.group20.docker.docker.DockerPackage#getRunCreateStatement_Commands()
   * @model
   * @generated
   */
  String getCommands();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group20.docker.docker.RunCreateStatement#getCommands <em>Commands</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Commands</em>' attribute.
   * @see #getCommands()
   * @generated
   */
  void setCommands(String value);

} // RunCreateStatement
